version: '3.9'

services:
  api-service-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: vcl-api-service-dev
    container_name: vcl-api-service-dev
    restart: unless-stopped
    ports:
      - "8065:8065"
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=8065
