version: '3.8'

services:
  express-ts:
    build:
      context: .
      dockerfile: Dockerfile
    image: vcl-api-service
    container_name: vcl-api-service
    restart: unless-stopped
    ports:
      - "8065:8065"
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=8065

