version: '3.9'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: vcl-api-service
    container_name: vcl-api-service
    restart: unless-stopped
    # export UID and GID to map your user to container root.
    # not necessary when using docker-rootless
    user: "${UID}:${GID}"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=8080
      # add uris that should be allowed by cors, separate by comma
      - CORS_ALLOWED=*
    volumes:
      # update the paths to provide local volumes
      - ./src/public:/app/dist/public
      - ./src/assets:/app/dist/assets
      - ./workshops:/app/dist/assets/workshops
